force-app/main/default/objects/ImplementationData__c/ImplementationData__c.object-meta.xml
<CustomObject>
    <label>Implementation Data</label>
    <nameField>
        <displayFormat>IDN{0000}</displayFormat>
        <label>Implementation Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ImplementationData__c/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ABN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImplementationData__c/fields/ElectricitySavingsMWh__c.field-meta.xml
<CustomField>
    <fullName>ElectricitySavingsMWh__c</fullName>
    <label>Electricity Savings(MWh)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImplementationData__c/fields/GasSavingsMWh__c.field-meta.xml
<CustomField>
    <fullName>GasSavingsMWh__c</fullName>
    <label>Gas Savings (MWh)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ImplementationData__c/fields/Implementation_Date__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Implementation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ImplementationData__c/fields/Postcode__c.field-meta.xml
<CustomField>
    <fullName>Postcode__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Postcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImplementationData__c/fields/Suburb__c.field-meta.xml
<CustomField>
    <fullName>Suburb__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Suburb</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ImplementationData__c/fields/WorkflowBatch__c.field-meta.xml
<CustomField>
    <fullName>WorkflowBatch__c</fullName>
    <label>Workflow Batch</label>
    <referenceTo>WorkflowBatch__c</referenceTo>
    <relationshipLabel>Implementation Data</relationshipLabel>
    <relationshipName>Implementation_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/WorkflowBatch__c.object-meta.xml
<CustomObject>
    <label>Workflow Batch</label>
    <nameField>
        <displayFormat>Batch{0000}</displayFormat>
        <label>Workflow Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkflowBatch__c/fields/Accreditation__c.field-meta.xml
<CustomField>
    <fullName>Accreditation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Accreditation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/fields/CertificateType__c.field-meta.xml
<CustomField>
    <fullName>CertificateType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Certificate Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/fields/NumberOfCerts__c.field-meta.xml
<CustomField>
    <fullName>NumberOfCerts__c</fullName>
    <label>Number of Certs</label>
    <summaryForeignKey>ImplementationData__c.WorkflowBatch__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Ownership</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reference #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowBatch__c/fields/Vintage__c.field-meta.xml
<CustomField>
    <fullName>Vintage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Vintage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowCertificate__c/WorkflowCertificate__c.object-meta.xml
<CustomObject>
    <label>Certificate</label>
    <nameField>
        <displayFormat>CER-{0000}</displayFormat>
        <label>Certificate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkflowCertificate__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>WorkflowBatch__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Workflow_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkflowCertificate__c/fields/WorkflowTask__c.field-meta.xml
<CustomField>
    <fullName>WorkflowTask__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workflow Task</label>
    <referenceTo>WorkflowTask__c</referenceTo>
    <relationshipLabel>Certificates</relationshipLabel>
    <relationshipName>Certificates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/WorkflowTask__c.object-meta.xml
<CustomObject>
    <label>Workflow Task</label>
    <nameField>
        <displayFormat>WTN-{0000}</displayFormat>
        <label>Workflow Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkflowTask__c/fields/CertType__c.field-meta.xml
<CustomField>
    <fullName>CertType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cert Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/fields/Number_Of_Certs__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Certs__c</fullName>
    <formula>WorkflowBatch__r.TotalNumberCerts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Number of Certs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Registrant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/fields/RESAPRSAIdentifier__c.field-meta.xml
<CustomField>
    <fullName>RESAPRSAIdentifier__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>RESA/PRSA Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/fields/Vintage__c.field-meta.xml
<CustomField>
    <fullName>Vintage__c</fullName>
    <formula>WorkflowBatch__r.Vintage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vintage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/fields/WorkflowBatch__c.field-meta.xml
<CustomField>
    <fullName>WorkflowBatch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Workflow Batch</label>
    <referenceTo>WorkflowBatch__c</referenceTo>
    <relationshipLabel>Workflow Tasks</relationshipLabel>
    <relationshipName>Workflow_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkflowTask__c/fields/WorkflowID__c.field-meta.xml
<CustomField>
    <fullName>WorkflowID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Workflow ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSVFileReadLWCCntrl.cls
public with sharing class CSVFileReadLWCCntrl {
    /*public CSVFileReadLWCCntrl() {

    }*/

    @AuraEnabled
    //public static list<Account> csvFileRead(Id contentDocumentId){
        public static list<WorkflowTask__c> csvFileRead(Id contentDocumentId){

        Boolean isFileNotCorrect = false;
        String taskMessage;
        //list<Account> accountInsertList = new list<Account>();
        //List<WorkflowTask__c> wtasksList = new List<WorkflowTask__c>();
        List<ImplementationData__c> impDataList = new List<ImplementationData__c>();    
        WorkflowTask__c wtaskObj = new WorkflowTask__c();

        if(contentDocumentId != null) {
            
            // Fetch File Data based on the basic of document id 
            ContentVersion contentVersionObj = [SELECT Id, VersionData FROM ContentVersion WHERE ContentDocumentId =:contentDocumentId];
            // split the file data
            list<String> csvRecordsList = contentVersionObj.VersionData.toString().split('\n');

            
            wtaskObj.Status__c = 'Initial Upload Complete';
            wtaskObj.RESAPRSAIdentifier__c = 'GHGR00011A/1';
            wtaskObj.CertType__c = 'ESC';
            wtaskObj.WorkflowID__c = '878111';                        

            WorkflowBatch__c wbFlowBatch = new WorkflowBatch__c();
            wbFlowBatch.Accreditation__c = 'RESA AQ2128';
            wbFlowBatch.CertificateType__c = 'ESC';
            wbFlowBatch.Ownership__c = 'EnergySafe Pty Ltd';
            wbFlowBatch.Range__c = '5500-5550';
            wbFlowBatch.Reference__c = 'Imp8188';
            wbFlowBatch.Status__c = 'Active';
            wbFlowBatch.Vintage__c = '2021';
            insert wbFlowBatch;


            wtaskObj.WorkflowBatch__c = wbFlowBatch.id;

            for(Integer i = 1; i < csvRecordsList.size(); i++){
                //Account accountObj = new Account();
                
                ImplementationData__c impData = new ImplementationData__c();
                list<String> csvRowData = csvRecordsList[i].split(',');
                System.debug('csvRowData====> '+csvRowData);

                impData.Implementation_Date__c = System.Date.today();
                //impData.Implementation_Date__c = Date.valueOf(csvRowData[0]);
                impData.Address_Line_1__c = csvRowData[1];
                impData.Address_Line_2__c = csvRowData[2];
                impData.Suburb__c = csvRowData[3];
                impData.State__c = csvRowData[4];
                impData.Postcode__c = csvRowData[5];
                impData.ABN__c = csvRowData[6];
                impData.ElectricitySavingsMWh__c = Integer.valueOf(csvRowData[7]);
                impData.GasSavingsMWh__c = 10;
                //impData.GasSavingsMWh__c = Integer.valueOf(csvRowData[8]);
                impData.WorkflowBatch__c = wbFlowBatch.Id;

                impDataList.add(impData);

                //wtaskObj.WorkflowID__c = csvRowData[0];
                //wtaskObj.Registrant__c = csvRowData[1];
                //wtaskObj.NumberOfCerts__c = Integer.valueOf(csvRowData[4]);
                //wtaskObj.Vintage__c = Integer.valueOf(csvRowData[5]);
                


                //accountObj.Name = csvRowData[0]; // accName
                //accountObj.AccountSource = csvRowData[1];
                //accountObj.Site = csvRowData[2];
                //accountObj.Type = csvRowData[3];
                //accountObj.Website = csvRowData[4];
                System.debug('isFineNotCorrect:::::' + isFileNotCorrect);
                System.debug('csvRowData[1]:::::' + csvRowData[1]);
                System.debug('csvRowData[1] ==null:::::' + csvRowData[1] ==null);    
                System.debug('csvRowData[1].length()==0:::::' + csvRowData[1].length()); 

                
                if(!isFileNotCorrect && (csvRowData[1] ==null  ||  csvRowData[1].length()==0)){                    
                    //taskMessage='Success';
                //}else{
                    //taskMessage='Error: No RESA PRSA Identifier Not Available';
                    isFileNotCorrect = true;
                }                
            
                //accountInsertList.add(accountObj);
            }

            System.debug('isFineNotCorrect:::::' + isFileNotCorrect);


            if(isFileNotCorrect){
                wtaskObj.Message__c = 'Error: Validation Failed';
            }else{
                wtaskObj.Message__c = 'Success';
            }
            insert wtaskObj;
            
            //wtasksList.add(wtaskObj);

            try{                
                if(!impDataList.isEmpty()) {
                    insert impDataList;
                }
                

                //if(!accountInsertList.isEmpty()) {
                    //insert accountInsertList;
                //if(!wtasksList.isEmpty()){
                //    insert wtasksList;

                    /*if(!isFileNotCorrect){
                        //Create a Workflow batch
                        WorkflowBatch__c wbc = new WorkflowBatch__c();
                        insert wbc;

                        //Create Certificate records
                        List<WorkflowCertificate__c> certList = new List<WorkflowCertificate__c>();
                        for(WorkflowTask__c wtc: wtasksList){

                            for(Integer i=0 ;  i < wtc.NumberOfCerts__c ; i++){
                            WorkflowCertificate__c cert = new WorkflowCertificate__c();
                            //cert.Account__c = acc.Id;
                            cert.Batch__c = wbc.Id;
                            cert.WorkflowTask__c = wtc.Id;

                            certList.add(cert);
                            }
                        }

                        if(!certList.isEmpty()){
                            insert certList;
                        }
                    }*/
                //}
            }
            catch (Exception ex) {
                throw new AuraHandledException(ex.getMessage());
            }
        }

        List<WorkflowTask__c> wtasksList = [select id,CertType__c,WorkflowID__c,Number_Of_Certs__c,Message__c,Vintage__c,RESAPRSAIdentifier__c from WorkflowTask__c where id = :wtaskObj.id];

        System.debug(wtasksList);
        //return accountInsertList;
        return  wtasksList;   
        //return null;
    }
}